#index:
#    path: /
#    controller: App\Controller\DefaultController::index


showApprenantById:
    path: /api/apprenants/{id}
    controller: App\Controller\UserController::showApprenantById
    methods: ['GET','PUT']

showFormateur:
    path: /api/formateurs
    controller: App\Controller\UserController::showFormateur
    methods: ['GET']

showFormateurById:
    path: /api/formateurs/{id}
    controller: App\Controller\UserController::showFormateurById
    methods: ['GET','PUT']

showApprenantByHisId:
    path: /api/apprenants/{id}
    controller: App\Controller\UserController::showApprenantByHisId
    methods: ['GET']


#config/routes.yaml
authentication_token:
    path: /api/login_check
    methods: ['POST']
