api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 6
